name: Deploy Snowflake Monitoring

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SQL scripts using Snowflake Action
        uses: snowflakedb/snowflake-action@v1
        with:
          account: ${{ secrets.SNOWSQL_ACCOUNT }}
          username: ${{ secrets.SNOWSQL_USER }}
          password: ${{ secrets.SNOWSQL_PWD }}
          region: aws
          warehouse: COMPUTE_WH
          database: ${{ secrets.SNOWSQL_DATABASE }}
          role: ACCOUNTADMIN
          script: |
            USE DATABASE ${{ secrets.SNOWSQL_DATABASE }};
            !source sql/01_create_known_tables.sql;
            !source sql/02_create_alert_log.sql;
            !source sql/03_create_procedure.sql;
            !source sql/04_create_task.sql;
            !source sql/05_create_alert.sql;
            ALTER TASK monitoring.detect_new_tables_task RESUME;
            ALTER ALERT monitoring.new_table_alert RESUME;
